import React from 'react';
export const complianceDetails = () => <div>compliance distinct</div>;
export const compliance_detail_0 = (p:any)=> <div>compliance 0 NSF 2-page</div>;
export const compliance_detail_1 = (p:any)=> <div>compliance 1 NIH 12pt</div>;
export const compliance_detail_2 = (p:any)=> <div>compliance 2 DOE 1-inch</div>;
export const compliance_detail_3 = (p:any)=> <div>compliance 3 margins</div>;
export const compliance_detail_4 = (p:any)=> <div>compliance 4 NSF 2-page</div>;
export const compliance_detail_5 = (p:any)=> <div>compliance 5 NIH 12pt</div>;
export const compliance_detail_6 = (p:any)=> <div>compliance 6 DOE 1-inch</div>;
export const compliance_detail_7 = (p:any)=> <div>compliance 7 margins</div>;
export const compliance_detail_8 = (p:any)=> <div>compliance 8 NSF 2-page</div>;
export const compliance_detail_9 = (p:any)=> <div>compliance 9 NIH 12pt</div>;
export const compliance_detail_10 = (p:any)=> <div>compliance 10 DOE 1-inch</div>;
export const compliance_detail_11 = (p:any)=> <div>compliance 11 margins</div>;
export const compliance_detail_12 = (p:any)=> <div>compliance 12 NSF 2-page</div>;
export const compliance_detail_13 = (p:any)=> <div>compliance 13 NIH 12pt</div>;
export const compliance_detail_14 = (p:any)=> <div>compliance 14 DOE 1-inch</div>;
export const compliance_detail_15 = (p:any)=> <div>compliance 15 margins</div>;
export const compliance_detail_16 = (p:any)=> <div>compliance 16 NSF 2-page</div>;
export const compliance_detail_17 = (p:any)=> <div>compliance 17 NIH 12pt</div>;
export const compliance_detail_18 = (p:any)=> <div>compliance 18 DOE 1-inch</div>;
export const compliance_detail_19 = (p:any)=> <div>compliance 19 margins</div>;