import React from 'react';
export const trackingDetails = () => <div>tracking distinct</div>;
export const tracking_detail_0 = (p:any)=> <div>tracking 0 Kanban</div>;
export const tracking_detail_1 = (p:any)=> <div>tracking 1 20 simultaneous</div>;
export const tracking_detail_2 = (p:any)=> <div>tracking 2 tracking</div>;
export const tracking_detail_3 = (p:any)=> <div>tracking 3 pipeline</div>;
export const tracking_detail_4 = (p:any)=> <div>tracking 4 Kanban</div>;
export const tracking_detail_5 = (p:any)=> <div>tracking 5 20 simultaneous</div>;
export const tracking_detail_6 = (p:any)=> <div>tracking 6 tracking</div>;
export const tracking_detail_7 = (p:any)=> <div>tracking 7 pipeline</div>;
export const tracking_detail_8 = (p:any)=> <div>tracking 8 Kanban</div>;
export const tracking_detail_9 = (p:any)=> <div>tracking 9 20 simultaneous</div>;
export const tracking_detail_10 = (p:any)=> <div>tracking 10 tracking</div>;
export const tracking_detail_11 = (p:any)=> <div>tracking 11 pipeline</div>;
export const tracking_detail_12 = (p:any)=> <div>tracking 12 Kanban</div>;
export const tracking_detail_13 = (p:any)=> <div>tracking 13 20 simultaneous</div>;
export const tracking_detail_14 = (p:any)=> <div>tracking 14 tracking</div>;
export const tracking_detail_15 = (p:any)=> <div>tracking 15 pipeline</div>;
export const tracking_detail_16 = (p:any)=> <div>tracking 16 Kanban</div>;
export const tracking_detail_17 = (p:any)=> <div>tracking 17 20 simultaneous</div>;
export const tracking_detail_18 = (p:any)=> <div>tracking 18 tracking</div>;
export const tracking_detail_19 = (p:any)=> <div>tracking 19 pipeline</div>;