import React from 'react';
export const budgetDetails = () => <div>budget distinct</div>;
export const budget_detail_0 = (p:any)=> <div>budget 0 SF-424</div>;
export const budget_detail_1 = (p:any)=> <div>budget 1 budget</div>;
export const budget_detail_2 = (p:any)=> <div>budget 2 justification</div>;
export const budget_detail_3 = (p:any)=> <div>budget 3 cost share</div>;
export const budget_detail_4 = (p:any)=> <div>budget 4 SF-424</div>;
export const budget_detail_5 = (p:any)=> <div>budget 5 budget</div>;
export const budget_detail_6 = (p:any)=> <div>budget 6 justification</div>;
export const budget_detail_7 = (p:any)=> <div>budget 7 cost share</div>;
export const budget_detail_8 = (p:any)=> <div>budget 8 SF-424</div>;
export const budget_detail_9 = (p:any)=> <div>budget 9 budget</div>;
export const budget_detail_10 = (p:any)=> <div>budget 10 justification</div>;
export const budget_detail_11 = (p:any)=> <div>budget 11 cost share</div>;
export const budget_detail_12 = (p:any)=> <div>budget 12 SF-424</div>;
export const budget_detail_13 = (p:any)=> <div>budget 13 budget</div>;
export const budget_detail_14 = (p:any)=> <div>budget 14 justification</div>;
export const budget_detail_15 = (p:any)=> <div>budget 15 cost share</div>;
export const budget_detail_16 = (p:any)=> <div>budget 16 SF-424</div>;
export const budget_detail_17 = (p:any)=> <div>budget 17 budget</div>;
export const budget_detail_18 = (p:any)=> <div>budget 18 justification</div>;
export const budget_detail_19 = (p:any)=> <div>budget 19 cost share</div>;