import React from 'react';
export const proposalsDetails = () => <div>proposals distinct</div>;
export const proposals_detail_0 = (p:any)=> <div>proposals 0 narrative</div>;
export const proposals_detail_1 = (p:any)=> <div>proposals 1 biosketch</div>;
export const proposals_detail_2 = (p:any)=> <div>proposals 2 budget justification</div>;
export const proposals_detail_3 = (p:any)=> <div>proposals 3 narrative</div>;
export const proposals_detail_4 = (p:any)=> <div>proposals 4 biosketch</div>;
export const proposals_detail_5 = (p:any)=> <div>proposals 5 budget justification</div>;
export const proposals_detail_6 = (p:any)=> <div>proposals 6 narrative</div>;
export const proposals_detail_7 = (p:any)=> <div>proposals 7 biosketch</div>;
export const proposals_detail_8 = (p:any)=> <div>proposals 8 budget justification</div>;
export const proposals_detail_9 = (p:any)=> <div>proposals 9 narrative</div>;
export const proposals_detail_10 = (p:any)=> <div>proposals 10 biosketch</div>;
export const proposals_detail_11 = (p:any)=> <div>proposals 11 budget justification</div>;
export const proposals_detail_12 = (p:any)=> <div>proposals 12 narrative</div>;
export const proposals_detail_13 = (p:any)=> <div>proposals 13 biosketch</div>;
export const proposals_detail_14 = (p:any)=> <div>proposals 14 budget justification</div>;
export const proposals_detail_15 = (p:any)=> <div>proposals 15 narrative</div>;
export const proposals_detail_16 = (p:any)=> <div>proposals 16 biosketch</div>;
export const proposals_detail_17 = (p:any)=> <div>proposals 17 budget justification</div>;
export const proposals_detail_18 = (p:any)=> <div>proposals 18 narrative</div>;
export const proposals_detail_19 = (p:any)=> <div>proposals 19 biosketch</div>;